<a href="https://colab.research.google.com/github/Aaryan8597/AI-ML-AaryanLamichhane2408597-/blob/main/Worksheet0.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Exercise on Functions

## Task-1 Creating a Python program that converts between different units of measurement

In [ ]:
#function for unit conversion
def convert_units(conversion_type, value):
  """
    Converts units for length, weight, and volume.
    conversion_type (int): type of conversion selected by the user
    value (float): value entered by the user
    returns
    float: converted result
    """
  if conversion_type == 1: #meters to feet
    return value * 3.28084
  elif conversion_type == 2: #feet to meters
    return value / 3.28084
  elif conversion_type == 3: #kilograms to pounds
    return value * 2.20462
  elif conversion_type == 4: #pounds to kilograms
      return value / 2.20462
  elif conversion_type == 5: #liters to gallons
      return value * 0.264172
  elif conversion_type == 6: #gallons to liters
      return value / 0.264172
  else:
      return None

print("Unit Conversion Program")
print("\nLength Conversion")
print("1. Meters to Feet")
print("2. Feet to Meters")
print("\nWeight Conversion")
print("3. Kilograms to Pounds")
print("4. Pounds to Kilograms")
print("\nVolume Conversion")
print("5. Liters to Gallons")
print("6. Gallons to Liters")

try:
    conversion_type = int(input("\nEnter conversion choice (1-6): "))
    value = float(input("Enter the value to convert: "))

    result = convert_units(conversion_type, value)
    if conversion_type >= 1 and conversion_type <= 6:
      print("Converted value:", result)
    else:
      print("Invalid conversion type.")

except ValueError:
    print("Error: Please enter a numeric value.")


Unit Conversion Program

Length Conversion
1. Meters to Feet
2. Feet to Meters

Weight Conversion
3. Kilograms to Pounds
4. Pounds to Kilograms

Volume Conversion
5. Liters to Gallons
6. Gallons to Liters

Enter conversion choice (1-6): 2
Enter the value to convert: 6
Converted value: 1.828799941478402


## Task-2 Creating a Python program that performs various mathematical operations on a list of numbers.

In [ ]:
def find_sum(numbers):
    """
    Calculate the sum of a list of numbers.
    numbers (list): list of numeric values
    Returns:
    float: sum of all numbers
    """
    return sum(numbers)

def find_average(numbers):
    """
    Calculate the average of a list of numbers.
    numbers (list): list of numeric values
    Returns:
    float: average value
    """
    return sum(numbers) / len(numbers)


def find_max(numbers):
    """
    Find the maximum number in the list.
    numbers (list): list of numeric values
    Returns:
    float: largest number in the list
    """
    return max(numbers)

def find_min(numbers):
    """
    Find the minimum number in the list.
    numbers (list): list of numeric values

    Returns:
    float: smallest number in the list
    """
    return min(numbers)

print("Mathematical Operations Program")
print("1. Find Sum")
print("2. Find Average")
print("3. Find Maximum")
print("4. Find Minimum")
try:
    operation = int(input("Choose an operation (1-4): "))
    numbers_input = input("Enter numbers separated by spaces: ")
    numbers_list = [float(num) for num in numbers_input.split()]
    if len(numbers_list) == 0:
        print("Error: The list is empty.")
    elif operation == 1:
        result = find_sum(numbers_list)
        print("Sum:", result)
    elif operation == 2:
        result = find_average(numbers_list)
        print("Average:", result)
    elif operation == 3:
        result = find_max(numbers_list)
        print("Maximum:", result)
    elif operation == 4:
        result = find_min(numbers_list)
        print("Minimum:", result)
    else:
        print("Invalid operation choice.")
except ValueError:
    print("Error: Please enter valid numeric values.")

Mathematical Operations Program
1. Find Sum
2. Find Average
3. Find Maximum
4. Find Minimum
Choose an operation (1-4): 2
Enter numbers separated by spaces: 12 13 14 15 16
Average: 14.0


# Exercise on List Manipulation

### Write a Python function that extracts every other element from a list, starting from the first element.

In [ ]:
def extract_every_other(first):
  new_list = first[::2]
  return new_list

numbers = [1,2,3,4,5,6]
result = extract_every_other(numbers)
print("Original List: ", numbers)
print("Every Other element: ", result)

Original List:  [1, 2, 3, 4, 5, 6]
Every Other element:  [1, 3, 5]


### Write a Python function that returns a sublist from a given list, starting from a specified index and ending at another specified index.

In [ ]:
def get_sublist(first, start, end):
  sublist = first[start:end+1]
  return sublist

numbers = [1,2,3,4,5,6]
result = get_sublist(numbers, 2, 4)
print("Original List: ", numbers)
print("Sublist: ", result)


Original List:  [1, 2, 3, 4, 5, 6]
Sublist:  [3, 4, 5]


### Write a Python function that reverses a list using slicing.

In [ ]:
def reverse_list(first):
  reversed_list = first[::-1]
  return reversed_list

numbers = [1, 2, 3, 4, 5]
result = reverse_list(numbers)
print("Original list:", numbers)
print("Reversed list:", result)

Original list: [1, 2, 3, 4, 5]
Reversed list: [5, 4, 3, 2, 1]


### Write a Python function that removes the first and last elements of a list and returns the resulting sublist.

In [ ]:
def remove_first_last(first):
  new_list = first[1:-1]
  return new_list

numbers = [1, 2, 3, 4, 5]
result = remove_first_last(numbers)
print("Original list:", numbers)
print("after removing first and last:", result)


Original list: [1, 2, 3, 4, 5]
after removing first and last: [2, 3, 4]


### Write a Python function that extracts the first n elements from a list.

In [ ]:
def get_first_n(first, n):
  return first[:n]

numbers = [1, 2, 3, 4, 5]
result = get_first_n(numbers, 2)
print("Original list:", numbers)
print("elements:", result)

Original list: [1, 2, 3, 4, 5]
elements: [1, 2]


### Write a Python function that extracts the last n elements of a list using slicing.

In [ ]:
def get_last_n(last, n):
  return last[-n:]

numbers = [1, 2, 3, 4, 5]
result = get_last_n(numbers, 2)
print("Original list:", numbers)
print("elements:", result)


Original list: [1, 2, 3, 4, 5]
elements: [4, 5]


### Write a Python function that extracts a list of elements in reverse order starting from the second-to-last element and skipping one element in between.

In [ ]:
def reverse_skip(first):
  return first[-2::-2]

numbers = [1, 2, 3, 4, 5, 6]
result = reverse_skip(numbers)
print("Original list:", numbers)
print("Reversed skip list:", result)

Original list: [1, 2, 3, 4, 5, 6]
Reversed skip list: [5, 3, 1]


# Exercise on Nested List

## Write a Python function that takes a nested list and flattens it into a single list, where all the elements are in a single dimension.

In [ ]:
def flatten(first):
  flat_list = []
  for sublist in first:
    flat_list.extend(sublist)
  return flat_list

nested_list = [[1, 2], [3, 4], [5, 6]]
result = flatten(nested_list)
print("Original nested list:", nested_list)
print("Flattened list:", result)

Original nested list: [[1, 2], [3, 4], [5, 6]]
Flattened list: [1, 2, 3, 4, 5, 6]


## Write a Python function that extracts a specific element from a nested list given its indices.

In [ ]:
def access_nested_element(first, indices):
  element = first
  for i in indices:
    element = element[i]
  return element

nested_list = [[1, 2, 3], [4, 5, 6], [7, 8, 9]]
indices = [1, 2]
result = access_nested_element(nested_list, indices)
print("Nested list:", nested_list)
print(f"Element at indices {indices}:", result)

Nested list: [[1, 2, 3], [4, 5, 6], [7, 8, 9]]
Element at indices [1, 2]: 6


## Write a Python function that calculates the sum of all the numbers in a nested list (regardless of depth).

In [ ]:
def sum_nested(first):
  total = 0
  for item in first:
    try:
      total += sum_nested(item)
    except TypeError:
      total += item
  return total

nested_list = [[1, 2], [3, [4, 5]], 6]
result = sum_nested(nested_list)
print("Nested list:", nested_list)
print("Sum of all elements:", result)

Nested list: [[1, 2], [3, [4, 5]], 6]
Sum of all elements: 21


## Write a Python function that removes all occurrences of a specific element from a nested list.

In [ ]:
def remove_element(first, elem):
  new_list = []
  for item in first:
      try:
          new_list.append(remove_element(item, elem))
      except TypeError:
          if item != elem:
              new_list.append(item)
  return new_list

first = [[1, 2], [3, 2], [4, 5]]
result = remove_element(first, 2)

print("Original list:", first)
print("Modified list:", result)

Original list: [[1, 2], [3, 2], [4, 5]]
Modified list: [[1], [3], [4, 5]]


## Write a Python function that finds the maximum element in a nested list (regardless of depth).

In [ ]:
def find_max(lst):
    max_value = 0
    for item in lst:
        if type(item) == list:
            value = find_max(item)
        else:
            value = item
        if value > max_value:
            max_value = value
    return max_value

numbers = [[1, 2], [3, [4, 5]], 6]
result = find_max(numbers)
print("Maximum element:", result)

Maximum element: 6


## Write a Python function that counts how many times a specific element appears in a nested list.

In [ ]:
def count_occurrences(lst, elem):
    count = 0
    for item in lst:
        if type(item) == list:
            count += count_occurrences(item, elem)
        elif item == elem:
            count += 1
    return count

lst = [[1, 2], [2, 3], [2, 4]]
result = count_occurrences(lst, 2)
print("Occurrences:", result)

Occurrences: 3


## Write a Python function that flattens a list of lists of lists into a single list, regardless of the depth.

In [ ]:
def deep_flatten(lst):
    result = []
    for item in lst:
        if type(item) == list:
            result += deep_flatten(item)
        else:
            result.append(item)
    return result

lst = [[[1, 2], [3, 4]], [[5, 6], [7, 8]]]
print(deep_flatten(lst))


[1, 2, 3, 4, 5, 6, 7, 8]


## Write a Python function that calculates the average of all elements in a nested list.

In [ ]:
def average_nested(lst):
    total_sum = 0
    total_count = 0
    for item in lst:
        if type(item) == list:
            sub_sum, sub_count = average_nested(item)
            total_sum += sub_sum
            total_count += sub_count
        else:
            total_sum += item
            total_count += 1
    return total_sum, total_count

numbers = [[1, 2], [3, 4], [5, 6]]
total_sum, total_count = average_nested(numbers)
average = total_sum / total_count
print("Average:", average)

Average: 3.5


# TO DO NUMPY

## Problem-1 Array creation

In [ ]:
import numpy as np
# initializing an empty array with size 2x2
empty_array = np.empty((2, 2))
print("Empty array:\n", empty_array)

#initializing an all one array with size 4x2
ones_array = np.ones((4, 2))
print("\nOnes array:\n", ones_array)

# new array of given shape and type, filled with fill value
full_array = np.full((3, 3), 7)
print("\nFull array:\n", full_array)

# new array of zeros with same shape and type as a given array
zeros_like_array = np.zeros_like(ones_array)
print("\nZeros like array:\n", zeros_like_array)

# new array of ones with same shape and type as a given array
ones_like_array = np.ones_like(ones_array)
print("\nOnes like array:\n", ones_like_array)

# For an existing list new_list = [1,2,3,4] convert to an numpy array.
new_list = [1, 2, 3, 4]
numpy_array = np.array(new_list)
print("\nList converted to NumPy array:\n", numpy_array)

Empty array:
 [[1.48688939e-315 0.00000000e+000]
 [2.44029516e-312 2.54639495e-312]]

Ones array:
 [[1. 1.]
 [1. 1.]
 [1. 1.]
 [1. 1.]]

Full array:
 [[7 7 7]
 [7 7 7]
 [7 7 7]]

Zeros like array:
 [[0. 0.]
 [0. 0.]
 [0. 0.]
 [0. 0.]]

Ones like array:
 [[1. 1.]
 [1. 1.]
 [1. 1.]
 [1. 1.]]

List converted to NumPy array:
 [1 2 3 4]


## Problem-2 Array Manipulation

In [ ]:
# create an array with values ranging from 10 to 49
array_10_49 = np.arange(10, 50)
print("Array from 10 to 49:\n", array_10_49)

# create a 3X3 matrix with values ranging from 0 to 8.
matrix_3x3 = np.arange(9).reshape((3, 3))
print("\n3x3 Matrix:\n", matrix_3x3)

# create a 3X3 identity matrix
identity_matrix = np.eye(3)
print("\n3x3 Identity Matrix:\n", identity_matrix)

# create a random array of size 30 and find the mean of the array
random_array = np.random.random(30)
mean_value = random_array.mean()
print("\nRandom array of size 30:\n", random_array)
print("Mean:", mean_value)

# create a 10X10 array with random values and find the minimum and maximum values
random_10x10 = np.random.random((10, 10))
min_value = random_10x10.min()
max_value = random_10x10.max()
print("\n10x10 Random array:\n", random_10x10)
print("Minimum value:", min_value)
print("Maximum value:", max_value)

# create a zero array of size 10 and replace 5th element with 1
zero_array = np.zeros(10)
zero_array[4] = 1
print("\nZero array with 5th element as 1:\n", zero_array)

# reverse an arraay arr = [1,2,0,0,4,0]
arr = np.array([1, 2, 0, 0, 4, 0])
reversed_arr = arr[::-1]
print("\nReversed array:\n", reversed_arr)

# create a 2d array with 1 border and 0 inside
border_array = np.ones((5, 5))
border_array[1:-1, 1:-1] = 0
print("\n2D array with border 1 and inside 0:\n", border_array)

# create 8x8 checkerboard pattern
checkerboard = np.zeros((8, 8))
checkerboard[1::2, ::2] = 1
checkerboard[::2, 1::2] = 1
print("\n8x8 Checkerboard pattern:\n", checkerboard)


Array from 10 to 49:
 [10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]

3x3 Matrix:
 [[0 1 2]
 [3 4 5]
 [6 7 8]]

3x3 Identity Matrix:
 [[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]

Random array of size 30:
 [0.34765782 0.73146137 0.65486942 0.43863918 0.73422273 0.99590197
 0.08505322 0.14255324 0.98229132 0.2301277  0.09059444 0.54863766
 0.32137507 0.27865328 0.73050296 0.05834237 0.83447593 0.0110758
 0.0447352  0.78678945 0.25429772 0.2180692  0.72748564 0.1584386
 0.68554808 0.38553823 0.0471434  0.56164426 0.67207399 0.26020602]
Mean: 0.43394684265750516

10x10 Random array:
 [[0.0027147  0.71673987 0.79460001 0.54722993 0.26035034 0.23880996
  0.34094483 0.56715127 0.6079836  0.87735441]
 [0.4315235  0.11568381 0.94493499 0.05407565 0.46677328 0.13843825
  0.46344415 0.78339429 0.68605719 0.84195056]
 [0.39536416 0.65232559 0.46184399 0.93792222 0.06370315 0.86127449
  0.08667822 0.23575478 0.45697376 0.48034156]

## Problem-3 Array Operations

In [ ]:
# adding, subtracting, multiplying two array
x = np.array([[1, 2], [3, 5]])
y = np.array([[5, 6], [7, 8]])
v = np.array([9, 10])
w = np.array([11, 12])

#adding x and y
sum_xy = x + y
print("Sum of x and y:\n", sum_xy)

#subtracting
diff_xy = x - y
print("\n2Difference of x and y:\n", diff_xy)

#multiplying of choice
multiply_x = x * 3
print("\nx multiplied by 3:\n", multiply_x)

#square of each element of th earray
square_x = x ** 2
print("\n4. Square of each element in x:\n", square_x)

# Dot product between v and w x and v x and y
dot_vw = np.dot(v, w)
dot_xv = np.dot(x, v)
dot_xy = np.dot(x, y)
print("\nDot products:")
print("v . w =", dot_vw)
print("x . v =", dot_xv)
print("x . y =\n", dot_xy)

# Concatenate
concat_xy_row = np.concatenate((x, y), axis=0)
concat_vw_col = np.vstack((v, w)).T
print("\nConcatenation:")
print("x and y along row:\n", concat_xy_row)
print("v and w along column:\n", concat_vw_col)

# Concatenate x and v
try:
    concat_xv = np.concatenate((x, v), axis=0)
except ValueError as e:
    concat_xv_error = e
print("\nConcatenate x and v error:")
print(concat_xv_error)

Sum of x and y:
 [[ 6  8]
 [10 13]]

2Difference of x and y:
 [[-4 -4]
 [-4 -3]]

x multiplied by 3:
 [[ 3  6]
 [ 9 15]]

4. Square of each element in x:
 [[ 1  4]
 [ 9 25]]

Dot products:
v . w = 219
x . v = [29 77]
x . y =
 [[19 22]
 [50 58]]

Concatenation:
x and y along row:
 [[1 2]
 [3 5]
 [5 6]
 [7 8]]
v and w along column:
 [[ 9 11]
 [10 12]]

Concatenate x and v error:
all the input arrays must have same number of dimensions, but the array at index 0 has 2 dimension(s) and the array at index 1 has 1 dimension(s)


## Problem-4 Matrix Operations

In [ ]:
# Prove following with Numpy:
A = np.array([[3, 4], [7, 8]])
B = np.array([[5, 3], [2, 1]])
print("Matrix A:\n", A)
print("Matrix B:\n", B)

# proving A.A−1 = I.
A_inv = np.linalg.inv(A)
identity = np.dot(A, A_inv)
print("\n1. A * A^-1:\n", identity)
print("Is approximately identity matrix:", np.allclose(identity, np.eye(2)))

# proving AB != BA
AB = np.dot(A, B)
BA = np.dot(B, A)
print("\nAB:\n", AB)
print("BA:\n", BA)
print("AB equals BA?", np.array_equal(AB, BA))

#proving (AB) T = BT AT
AB_transpose = AB.T
B_transpose_A_transpose = np.dot(B.T, A.T)
print("\n(AB)^T:\n", AB_transpose)
print("B^T * A^T:\n", B_transpose_A_transpose)
print("Are they equal?", np.allclose(AB_transpose, B_transpose_A_transpose))

Matrix A:
 [[3 4]
 [7 8]]
Matrix B:
 [[5 3]
 [2 1]]

1. A * A^-1:
 [[1.00000000e+00 0.00000000e+00]
 [1.77635684e-15 1.00000000e+00]]
Is approximately identity matrix: True

AB:
 [[23 13]
 [51 29]]
BA:
 [[36 44]
 [13 16]]
AB equals BA? False

(AB)^T:
 [[23 51]
 [13 29]]
B^T * A^T:
 [[23 51]
 [13 29]]
Are they equal? True


In [ ]:
# solving the following system of linear equation using inverse methods
# 2x − 3y + z = −1
# x − y + 2z = −3
# 3x + y − z = 9

coeff_matrix = np.array([[2, -3, 1],
                         [1, -1, 2],
                         [3, 1, -1]])
const_matrix = np.array([-1, -3, 9])

coeff_inv = np.linalg.inv(coeff_matrix)
solution = np.dot(coeff_inv, const_matrix)
print("\nSolution using inverse method:", solution)



Solution using inverse method: [ 2.  1. -2.]


# Experiment how fast is numpy


## Element wise Addition

In [ ]:
import time
size = 1_000_000
#creating two list
list1 = list(range(size))
list2 = list(range(size))
#measuring time for element wise additions
start_time = time.time()
list_sum = [list1[i] + list2[i] for i in range(size)]
end_time = time.time()
print("Python List Addition Time:", end_time - start_time, "seconds")

# using numpy arrays
array1 = np.arange(size)
array2 = np.arange(size)
#measuring time for element wise addition
start_time = time.time()
array_sum = array1 + array2
end_time = time.time()
print("NumPy Array Addition Time:", end_time - start_time, "seconds")

Python List Addition Time: 0.0712270736694336 seconds
NumPy Array Addition Time: 0.0028786659240722656 seconds


## Element-wise Multiplication

In [ ]:
size = 1_000_000
list1 = list(range(size))
list2 = list(range(size))
#measuring time for element wise multiplication
start_time = time.time()
list_product = [list1[i] * list2[i] for i in range(size)]
end_time = time.time()
print("Python List Multiplication Time:", end_time - start_time, "seconds")

array1 = np.arange(size)
array2 = np.arange(size)
#measuring time for element wise multiplication
start_time = time.time()
array_product = array1 * array2
end_time = time.time()
print("NumPy Array Multiplication Time:", end_time - start_time, "seconds")

Python List Multiplication Time: 0.06826472282409668 seconds
NumPy Array Multiplication Time: 0.0018911361694335938 seconds


## Dot Product

In [ ]:
size = 1_000_000
list1 = list(range(size))
list2 = list(range(size))
#measuring time
start_time = time.time()
dot_list = sum(list1[i] * list2[i] for i in range(size))
end_time = time.time()
print("Python List Dot Product Time:", end_time - start_time, "seconds")
array1 = np.arange(size)
array2 = np.arange(size)
#measuring time
start_time = time.time()
dot_array = np.dot(array1, array2)
end_time = time.time()
print("NumPy Array Dot Product Time:", end_time - start_time, "seconds")

Python List Dot Product Time: 0.06424641609191895 seconds
NumPy Array Dot Product Time: 0.0008299350738525391 seconds


## Matrix Multiplication


In [ ]:
size = 1000
# Creating two 1000x1000 matrices as lists of lists
matrix1 = [[i + j for j in range(size)] for i in range(size)]
matrix2 = [[i + j for j in range(size)] for i in range(size)]
start_time = time.time()
# Matrix multiplication using plain Python
result_list = [[0 for _ in range(size)] for _ in range(size)]
for i in range(size):
    for j in range(size):
        for k in range(size):
            result_list[i][j] += matrix1[i][k] * matrix2[k][j]
end_time = time.time()
print("Python List Matrix Multiplication Time:", end_time - start_time, "seconds")
# Create two 1000x1000 NumPy arrays
array1 = np.arange(size*size).reshape(size, size)
array2 = np.arange(size*size).reshape(size, size)
start_time = time.time()
# Matrix multiplication using NumPy
result_array = np.dot(array1, array2)
end_time = time.time()
print("NumPy Array Matrix Multiplication Time:", end_time - start_time, "seconds")

Python List Matrix Multiplication Time: 268.3748288154602 seconds
NumPy Array Matrix Multiplication Time: 0.7882258892059326 seconds
